version: '2.2'

services:
    activies-app:
        build: .
        container_name: activies-app
        entrypoint: ./.docker/entrypoint.sh
        ports: 
            - 3000:3000
        volumes: 
            - .:/home/node/activies-tracker
    db:
        image: mysql:8.0.25
        container_name: activies-app-db
        restart: always
        tty: true
        ports: 
            - "3306:3306"
        volumes: 
            - activies-app-dbdata:/var/lib/mysql
        environment: 
            - MYSQL_DATABASE=activies-app
            - MYSQL_ROOT_PASSWORD=root
        command: --default-authentication-plugin=caching_sha2_password

    adminer:
        image: adminer
        restart: always
        ports:
            - 8888:8080 

volumes: 
    activies-app-dbdata:
        external: true